// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AlphaApi.Models;
[Table("ConfiguracionToken", Schema = "mielor")]
public partial class ConfiguracionToken
{
    public int Id { get; set; }

    public int TiempoValidez { get; set; }
}