// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AlphaApi.Models;

public partial class ElorAutenticatorContext : DbContext
{
    public ElorAutenticatorContext(DbContextOptions<ElorAutenticatorContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ConfiguracionToken> ConfiguracionTokens { get; set; }

    public virtual DbSet<RegisterTokenRequest> RegisterTokenRequests { get; set; }

    public virtual DbSet<Tokens> Tokens { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ConfiguracionToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Configur__3214EC076475D4B3");

            entity.ToTable("ConfiguracionToken");
        });

        modelBuilder.Entity<RegisterTokenRequest>(entity =>
        {
            entity.ToTable("RegisterTokenRequest");

            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.Token).IsUnicode(false);
        });

        modelBuilder.Entity<Tokens>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Tokens__3214EC07D806447B");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.FechaExpiracion).HasColumnType("datetime");
            entity.Property(e => e.FechaUso).HasColumnType("datetime");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(6)
                .HasColumnName("Token");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}