// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AlphaApi.Models;
[Table("RegisterTokenRequest", Schema = "mielor")]
public partial class RegisterTokenRequest
{
    public int Id { get; set; }

    public string Token { get; set; }

    public DateTime? FechaCreacion { get; set; }
}