// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AlphaApi.Models;
[Table("Tokens", Schema = "mielor")]
public partial class Tokens
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Token { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime FechaExpiracion { get; set; }

    public DateTime? FechaUso { get; set; }
}